schedule: &schedule
  air_quality_importer:
    class: AirQualityImportCronJob
    queue: importer
    schedule: every 5 minutes

production:
  <<: *schedule

development:
  <<: *schedule

# production:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day
